name: Django Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: djangorestdb
        ports: ['3306:3306']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencis
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Migrations
      run: python manage.py migrate
      env: 
        DBENGINE: django.db.backends.mysql
        DBNAME: djangorestdb
        DBUSER: root
        DBPASSWORD: root
        DBHOST: 127.0.0.1
        DBPORT: 3306
    - name: Run Tests
      run: |
        python3 manage.py test
      env: 
        DBENGINE: django.db.backends.mysql
        DBNAME: djangorestdb
        DBUSER: root
        DBPASSWORD: root
        DBHOST: 127.0.0.1
        DBPORT: 3306


